# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sravel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sravel
pod 'SnapKit', '~> 5.6.0'
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'

end
