# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sravel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sravel
pod 'SnapKit', '~> 5.6.0'
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'GoogleMaps', '7.0.0'
pod 'GooglePlaces', '7.0.0'

end

target 'SravelTests' do
  use_frameworks!
  inherit! :search_paths
  # Pods for testing
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  end
